<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-KnowVault.Ingestion-e714f81a-7427-41b2-bbc4-2d21f00364a2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.4.6" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.4.6" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Search.Documents" Version="12.0.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.61.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KnowVault.ServiceDefaults\KnowVault.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Shared\KnowVault.Contracts\KnowVault.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\KnowVault.Domain\KnowVault.Domain.csproj" />
  </ItemGroup>
</Project>
